apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: backend-route
  namespace: mrogern-tenorio-dev
spec:
  to:
    kind: Service
    name: backend
    weight: 100
  port:
    targetPort: http    # CORRIGIDO
  tls:
    termination: edge
