name: Backend CI/CD

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout cÃ³digo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login no GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: env:
        username: marcustenorio
#       username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # BUILD + TAG :latest + TAG :sha
    # -------------------------------
    - name: Build da imagem Backend
      run: |
        IMAGE_SHA="ghcr.io/${{ github.actor }}/techroute-backend:${{ github.sha }}"
        IMAGE_LATEST="ghcr.io/${{ github.actor }}/techroute-backend:latest"

        echo "IMAGE_SHA=$IMAGE_SHA" >> $GITHUB_ENV
        echo "IMAGE_LATEST=$IMAGE_LATEST" >> $GITHUB_ENV

        docker build -t "$IMAGE_SHA" -t "$IMAGE_LATEST" backend

    - name: Push da imagem para GHCR
      run: |
        docker push "$IMAGE_SHA"
        docker push "$IMAGE_LATEST"

    # -------------------------------
    # INSTALA OC
    # -------------------------------
    - name: Install oc CLI
      run: |
        curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz -o oc.tar.gz
        tar -xzvf oc.tar.gz
        sudo mv oc /usr/local/bin/oc
        sudo mv kubectl /usr/local/bin/kubectl
        sudo chmod +x /usr/local/bin/oc /usr/local/bin/kubectl
        oc version --client

    # ---------------
    # LOGIN NO OPENSHIFT
    # -------------------------------
    - name: Login no OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OC_SERVER }}
        openshift_token: ${{ secrets.OC_TOKEN }}
        insecure_skip_tls_verify: true

    # -------------------------------
    # ATUALIZA O DEPLOYMENT
    # SEMPRE APONTANDO PARA :latest
    # -------------------------------
    - name: Atualizar Deployment no OpenShift
      run: |
        oc project ${{ secrets.OC_NAMESPACE }}
        oc set image deployment/backend backend="$IMAGE_LATEST" --record

    - name: Aguardar rollout
      run: |
        oc rollout status deployment/backend
#FIM
